using MailKitMigrationSample.Models;

namespace MailKitMigrationSample.Services;

public static class SampleMessageFactory
{
    public static MailMessage Create()
    {
        var message = new MailMessage
        {
            From = new MailAddress("sender@example.com", "Legacy Sender"),
            Subject = "Welcome to MailKit",
            Body = "<h1>Welcome</h1><p>This message was generated by the MailKit migration sample.</p>",
            IsBodyHtml = true
        };

        message.To.Add(new MailAddress("recipient@example.com", "Primary Recipient"));
        message.Cc.Add(new MailAddress("reviewer@example.com", "Delivery Reviewer"));

        return message;
    }
}
