FROM rockylinux:9

RUN dnf install -y unixODBC-devel curl tar gzip && \
    curl https://x-up.s3.amazonaws.com/7.x/<version>/... -o /tmp/exasol.tar.gz && \
    tar -xzf /tmp/exasol.tar.gz -C /tmp && \
    mv /tmp/EXASolution_ODBC-* /usr/lib64/

COPY config/odbcinst.ini /app/config/odbc/odbcinst.ini
COPY config/odbc.ini /app/config/odbc/odbc.ini
