using System.IO.Compression;
using AspxMigrationSample.Models;

namespace AspxMigrationSample.Services;

public sealed class PageService
{
    public PageDataResponse GetPageData(PageRequest request)
    {
        return new PageDataResponse
        {
            SpaceLabel = "Finance Administration",
            SpaceID = "SPACE-42",
            Schema = "finance_prod",
            DirectoryID = "DIR-1001",
            CurrentUser = "demo.user",
            Version = "vNext",
            DateLabel = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss 'UTC'"),
            PageDetails = !request.IsLite,
            IsAccountAdmin = true,
            Products =
            [
                new ProductRow
                {
                    ProductId = "P-100",
                    AccountType = "Enterprise",
                    ProductName = "Revenue Explorer"
                },
                new ProductRow
                {
                    ProductId = "P-200",
                    AccountType = "Standard",
                    ProductName = "Usage Dashboard"
                }
            ]
        };
    }

    public byte[] BuildPageExport()
    {
        using var stream = new MemoryStream();
        using (var archive = new ZipArchive(stream, ZipArchiveMode.Create, leaveOpen: true))
        {
            var entry = archive.CreateEntry("Page.txt");
            using var writer = new StreamWriter(entry.Open());
            writer.WriteLine("Legacy page export");
            writer.WriteLine("Generated by ASP.NET Core sample");
        }

        return stream.ToArray();
    }
}
